name: Deploy APK to Oracle VM

on:
  push:
    branches:
      - main # Workflow chạy khi có code push lên nhánh main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17' # Môi trường Java cần thiết để build Android

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true # Bật cache để các lần build sau nhanh hơn

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK (Release)
        run: flutter build apk --release

      - name: Deploy APK to Oracle VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "build/app/outputs/flutter-apk/app-release.apk"
          target: "/home/ubuntu/projects/AppInstall/"
          strip_components: 4 # Xóa 4 cấp thư mục (build/app/outputs/flutter-apk) để file ném thẳng vào target
          rm: true # Cờ này sẽ xóa sạch thư mục /home/ubuntu/projects/AppInstall/ trước khi copy file mới lên
